home: /codewind-workspace/.appsody
images: index.docker.io
lastversioncheck: 9999-12-31 23:59:59 +0000 UTC
operator: https://github.com/appsody/appsody-operator/releases/latest/download
tektonserver: ""
